source 'https://rubygems.org'

gem 'rails', '3.2.13'

gem 'bcrypt-ruby', '~> 3.0.0'
gem 'foreman'
gem 'haml-rails'
gem 'mechanize'
gem 'money-rails'
gem 'sqlite3'
gem 'unicorn'

# Gems used only for assets and not required in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
end

group :test do
  gem 'rspec-rails'
  gem 'capybara'
end
